name: Docker Image CI

on: [push]

jobs:
  sast_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Set SonarQube Token
        run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        with:
           sonar_token: ${{ secrets.SONAR_TOKEN }}
   
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag netflix-clone:$(date +%s)
